### ISSUE TITLE
Hand-Picked Products block limited to 11 products

### ISSUE THREAD

**Issue by WiredWonder** [woocommerce/woocommerce-gutenberg-products-block#4505]
## Describe the bug
For some reason the hand-picked products block only allows selecting 11 products.

Furthermore it counts up to 11 products in the block editor however overrides the last selected product without any warning or error.

## To reproduce

1. Add more than 11 products to the block

## Expected behavior
Allow me to add as many products as I want

## Screenshots
![image](https://user-images.githubusercontent.com/1524468/126854352-7060fc04-6a5c-4e99-92ad-5da0e6b9b383.png)

### WordPress (please complete the following information):
* Core version: 5.7.2
* Gutenberg version (if installed): na
* WooCommerce version: 5.5.2
* WooCommerce Blocks version: [e.g. 1.3.1]
* Site language: en
* Any other plugins installed: of course (none relevant to issue)

### Desktop (please complete the following information):
* OS: not relevant
* Browser not relevant
* Version not relevant

### Smartphone (please complete the following information):
* Device: not relevant
* OS: not relevant
* Browser not relevant
* Version not relevant

**Comment by mikejolley** [comment]
I don't appear to have this issue:
![Screenshot 2021-07-29 at 12 56 30](https://user-images.githubusercontent.com/90977/127487789-c52c1dad-ed4d-40d2-ba99-20e2ec3e5e15.png)

How many products are in your store total?

I see you've labelled everything "not relevant" to the issue, but it would be useful to at least add the status report from woocommerce.

Thanks

**Comment by WiredWonder** [comment]
Hey @mikejolley ,

I have just under 5000 items.

I would prefer not to post a full list of all software running on my site on a public bugtracker for security reasons; more than happy to share this in a more secure way if there is one.

To hopefully clarify the problem a little more;

Your screenshot only shows the initial block product setup screen. I can add many items there too. My screenshot is showing the right hand settings panel, adding items to the block after the page has been initially saved. 

Furthermore there seems to be some kind of weird interaction with the search widget, I can't quite put my finger on reproducing it exactly but I have multiple instances of the block now where I can't add any more items, but it's not always 10.

It's also worth mentioning that you need to refresh the page to ensure they have all been saved to the block correctly as the counter can lie.

Cheers,
Jason

**Comment by mikejolley** [comment]
Ok, the original testing instructions did not say this.

![Screenshot 2021-08-02 at 10 43 25](https://user-images.githubusercontent.com/90977/127840950-cdad4fff-c8c5-4833-b3ae-3a4eb6815c2c.png)

- Sidebar is the same. They actually use the same component so I wouldn't expect different behaviour in the sidebar.
- Tested with multiple handpicked blocks, no change.
- Tested after saving the page, no change.
- Search also makes no difference - the list is narrowed but the product list stays the same.

I would suggest testing for plugin conflicts but without a report, I have no idea what else you're running alongside blocks. Additionally, seeing if the theme is affecting the number of products shown.

This is currently not reproducible. @Aljullu is handpicked products also working for you?

**Comment by Aljullu** [comment]
> @Aljullu is handpicked products also working for you?

Working on my end as well @mikejolley. One thing that might be related to the issue is whether there are more than 100 products in the store. I know the logic to retrieve them is a bit different:

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/ea3347b1e391a30f26f061ea0f598e4dc5df39ac/assets/js/editor-components/utils/index.js#L24

**Comment by WiredWonder** [comment]
Are you both testing with > 100 products in the store? As I said above, I have nearly 5000.

Happy to share a report if there's a secure way.

**Comment by WiredWonder** [comment]
@mikejolley can we leave this open until it's been tested? there is not even a build I can use to verify it's closed. Thanks.

**Comment by mikejolley** [comment]
@galapogos01 it has been tested by our team. It will be in the next feature plugin release.

**Comment by WiredWonder** [comment]
@mikejolley last time we spoke you couldn't reproduce the issue. How are you sure it's resolved if I haven't retested?

**Comment by mikejolley** [comment]
@galapogos01 Because I was able to reproduce the issue after adding more products. We don't keep issues open once a fix has been merged. If you encounter further problems after testing the fix above, or updating, please open a fresh issue.

**Comment by WiredWonder** [comment]
Hi @mikejolley can you confirm if this was in the WooCommerce 5.6.0 release? Release notes say

> WooCommerce Blocks 5.4.1, and 5.5.1. These updates contain a number of enhancements, bug fixes, and some improvements to allow products to be added by SKU in the Hand-Picked Products block.

However I am still experiencing the bug.

edit: to reproduce this bug, one must add items up to (or greater than) 10, save the widget, and then attempt to add more through multiple searches. You will find it starts replacing items past 11, as every time you search for something else, it re-calculates the current "products selected" list it only retrieves 10 items.

**Comment by mikejolley** [comment]
@galapogos01 This fix went into Blocks 5.7.0. See the milestone in https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/4534

WooCommerce core (5.6) includes Blocks 5.5 (seen here https://github.com/woocommerce/woocommerce/blob/5.6.0/composer.json#L25) so you won't be able to test this fix until the next WooCommerce core major update, or if you use the [Blocks feature plugin](https://wordpress.org/plugins/woo-gutenberg-products-block/).

Thanks

**Comment by WiredWonder** [comment]
Thank you, confirming it has been fixed in Blocks 5.7.0.
