### ISSUE TITLE
After the update my checkout disappeared

### ISSUE THREAD

**Issue by msroky** [woocommerce/woocommerce-gutenberg-products-block#4881]
When I did the update, the checkout page disappeared, I had to add it again but I don't have the option to make some fields mandatory or to add a field for the company, etc.

Please fix this as soon as possible.

**Comment by senadir** [comment]
Hey there @msroky, what version of WooCommerce Blocks are you running? This was fixed in 6.0.1 without any intervention from you.

> I had to add it again but I don't have the option to make some fields mandatory or to add a field for the company, etc.

This has been moved further down the line, so you need to select the Shipping Address step now:
![image](https://user-images.githubusercontent.com/6165348/135639608-794f6d27-5339-430f-8a78-188d85083c1b.png)

**Comment by ralucaStan** [comment]
@msroky I’m going to close this because there still isn’t anything actionable for us on this issue. If/when you have additional details, you can still add them to this issue and if we’re able to reproduce we can re-open as necessary.
