### ISSUE TITLE
Translation Compatibility Issue with Preferred Languages

### ISSUE THREAD

**Issue by masteradhoc** [woocommerce/woocommerce-gutenberg-products-block#6391]
## Describe the bug
see a full description here: https://github.com/swissspidy/preferred-languages/issues/466

1) installed woocommerce & woocommerce blocks from wp repo
2) installed the WP feature plugin "Preferred Languages" (https://wordpress.org/plugins/preferred-languages/) with these settings configured
![image](https://user-images.githubusercontent.com/6242098/166255077-54cfed0c-9718-44be-96aa-01c9525005cf.png)

Quick Note of what the plugin solves: (common issue in german language)
_"This plugin lets you select multiple preferred languages in your settings. WordPress then tries to load the translations for the first language that's available, falling back to the next language in your list. This works great when you want to display WordPress in a locale like German (formal) and have it fall back to informal German when there's no translation available."
=> Now as the Swiss Translation is partially there i activated a filter that goes on a string level instead language level.

3) Although this perfectly works on all other plugins i saw for woo blocks i still see some strings in english as f.e. on the cart
"Proceed to checkout" as example
![image](https://user-images.githubusercontent.com/6242098/166255210-93c5093a-2fcf-4a93-a794-09bb954b1146.png)

4) let's check the flow of the strings.

step a (not found, correct): https://translate.wordpress.org/projects/wp-plugins/woo-gutenberg-products-block/stable/de-ch/informal/?filters%5Bterm%5D=proceed&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

step b (not found, correct): https://translate.wordpress.org/projects/wp-plugins/woo-gutenberg-products-block/stable/de-ch/default/?filters%5Bterm%5D=proceed&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

step c (not found, incorrect): https://translate.wordpress.org/projects/wp-plugins/woo-gutenberg-products-block/stable/de/default/?filters%5Bterm%5D=proceed&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

On Step C the translation should be found and shown.

Same also happens f.e. on "shipping method"
[Step A](https://translate.wordpress.org/projects/wp-plugins/woo-gutenberg-products-block/stable/de-ch/informal/?filters%5Bterm%5D=shipping+method&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc) -> [Step B](https://translate.wordpress.org/projects/wp-plugins/woo-gutenberg-products-block/stable/de-ch/default/?filters%5Bterm%5D=shipping+method&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc) -> [Step C](https://translate.wordpress.org/projects/wp-plugins/woo-gutenberg-products-block/stable/de/default/?filters%5Bterm%5D=shipping+method&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc)

---

Plugin Developer Response

_"As for the missing translation, not sure what's going on at first glance.

But as you can see at https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/woocommerce-gutenberg-products-block.php, which you pointed to, the WooCommerce Blocks plugin has some very custom logic for loading translations.

It is very likely that this custom logic is not compatible with the way Preferred Languages works. Especially if translations otherwise work fine for your other plugins.

In that case I recommend reaching out to them about fixing this."_

## Expected behavior
WooCommerce Blocks allows a compatibility with the wordpress feature project.

Let me know if you need more details for anything :)

**Comment by tomasztunik** [comment]
We'd appreciate updating the description with a quick summary of the issue here, what is the conflict, what are the steps to reproduce the issue, and what are the expected outcomes. This will make it easier for us to understand the problem and see how we can help.

Before we go into details as mini-cart and some of the features there are still developing I wanted to check in with you and confirm that the missing strings are correctly translated into your languages of choice. I believe you are after Swiss German right? 

https://translate.wordpress.org/locale/de-ch/default/wp-plugins/woo-gutenberg-products-block/ It seems like most of the plugin is not translated yet.

**Comment by masteradhoc** [comment]
@tomasztunik done now :) let me know if you need more details!

Hope this also clears the question why the strings still should show although they are not fully translated yet.

**Comment by tomasztunik** [comment]
Thank you! this will help us a lot when it moves hands. Moving it into the pipeline.

Looking at the description, how we hook into the translations might interfere with other translations related extensions. Needs more research.

**Comment by senadir** [comment]
This issue seems to reflect a similar issue we had in which translation isn't loading for some inner blocks, and should be fixed by #6420

**Comment by masteradhoc** [comment]
Thanks @senadir looking forward to the update :)

**Comment by masteradhoc** [comment]
@senadir just checked and looks very good! only translation issue that still persists is this one string.
![image](https://user-images.githubusercontent.com/6242098/170718884-fda98da5-2e97-4ba3-8f02-f1ec21a91311.png)
at cart right side. Can u check?

Translation would be there: https://translate.wordpress.org/projects/wp-plugins/woo-gutenberg-products-block/stable/de/default/?filters%5Bterm%5D=shipping+method&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

**Comment by senadir** [comment]
Hey @masteradhoc I have the same issue on different locals and I didn't figure out why it happens yet, I will keep you updated once it's fixed.
